# Generated by Django 4.2.7 on 2025-09-11 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalentry',
            options={'ordering': ['-date', '-created_at'], 'verbose_name_plural': 'Journal Entries'},
        ),
        migrations.AlterUniqueTogether(
            name='journalentry',
            unique_together=set(),
        ),
    ]
